# Generated by Django 5.1.2 on 2024-11-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='uday', max_length=100),
            preserve_default=False,
        ),
    ]
